### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sgarciahelguera** [Cubeseed/Backend#10]
Check: https://www.django-rest-framework.org/api-guide/testing/
 - [x] understand a good way to organize run setup testing
 - [x] add test cases for existing endpoints
 - [x] add how to run tests, create tests, etc. somewhere
 - [x] setup git to run tests and require tests succeed to merge a PR

**Comment by sgarciahelguera** [comment]
PR #23 added an action to run tests on PR.

**Comment by sgarciahelguera** [comment]
This progressed a lot, we are only missing a doc (somewhere in the general readme or a wiki page and a link to it in the general readme).
PR #23 added a runner that does `python manage.py test` so that's a way to run tests. 
Maybe we should also point to a way to run a single test and of course a minor point on how to add a test, a link to general documentation would be fine also
@mihrab34 do you think you can do that?

**Comment by mihrab34** [comment]
@sgarciahelguera A link on how to add a test (preferably the one added in the first comment) can be added somewhere in the wiki page. And the `python manage.py test` can be included in the ReadMe under a **Run Test** section
