### ISSUE TITLE
Add FarmerProfile

### ISSUE THREAD

**Issue by sgarciahelguera** [Cubeseed/Backend#15]
Should inherit from UserProfile or be related.
UserProfile is generic and any user type has one and puts whatever he likes in it (logged in as the owner you can edit it, only you can see content, maybe a moderator? moderator needs to see identifying stuff, but maybe it is enough for it to see User and not UserProfile ).

**FarmerProfile**:

1. List of **Course certificates** (files)
2. Review status, one of : "PENDING", "REJECTED", "APPROVED" 
3. ~List of **Crops**~
4. ~List of **Livestock**~

Courses are on business not farming, so crops and livestock goes out of here and into the farms only (at least for now).

**Comment by sgarciahelguera** [comment]
I think it may be useful for each course certificate to have it's own review status, independant from the one in the farmer profile 
So if there are many the moderator can go one by one , or maybe two different moderators can review different types of documents
So, also, we should store who approved something (for both the farmer profile review status, and each document review status)

**Comment by MiebiB** [comment]
Are we only considering what the moderator will be reviewing?

**Comment by shawnkoong** [comment]
I was just going to start off with @sgarciahelguera's input above, to create a model/entity for the back end. @MiebiB do you have particular thoughts?

**Comment by MiebiB** [comment]
No, I was just trying to understand what was going on

**Comment by sgarciahelguera** [comment]
This issue should be about the farmer profile, that is what is not in the general user profile already.

**Comment by sgarciahelguera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to be added on Cubeseed](https://trello.com/c/3qDdaEME/2-i-want-to-be-added-on-cubeseed)
