### ISSUE TITLE
Business Profile

### ISSUE THREAD

**Issue by sgarciahelguera** [Cubeseed/Backend#4]
- [-] BusinessProfile
   + [ ] Define API
   + [X] Define data model & use cases
   + [ ] Implementation
   + [ ] Integration

**Comment by sgarciahelguera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define Business Profile API and entities, implement, test](https://trello.com/c/5fgjp09v/16-define-business-profile-api-and-entities-implement-test)

**Comment by sgarciahelguera** [comment]
This still needs a lot of work on design, specifications, definitions, etc...  (issue #9 )
Maybe worth to do a basic version of it but keep that in mind, it will change.

**Comment by Natiman58** [comment]
> [-] BusinessProfile
> * [ ]  Define API
> * [x]  Define data model & use cases
> * [ ]  Implementation
> * [ ]  Integration

working on defining the RESTFUL APIs for the businessProfile model
