### ISSUE TITLE
Working on the purchase order generator model API

### ISSUE THREAD

**Issue by Natiman58** [Cubeseed/Backend#68]

**Comment by Reid-T-W** [comment]
Is this the task you're working on Nati?
[I want to receive purchase orders and contracts](https://trello.com/c/MFltvQer).

**Comment by Reid-T-W** [comment]
I was assigned to it but If you're working on it, kindly let me know and I'll move on to another task.

**Comment by Natiman58** [comment]
I'm almost done with it and sorry I didn't see your issue that's why I started working on it

**Comment by Reid-T-W** [comment]
No worries, I just wanted to be sure before I started working on another task.
